name: Build Python Wrapper for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Eigen3 (no Fortran)
      shell: bash
      run: |
        mkdir -p deps
        if [ -d "deps/Eigen3" ]; then
          rm -rf deps/Eigen3
        fi
        git clone -b 3.4.0 --depth 1 https://gitlab.com/libeigen/eigen.git deps/Eigen3
        # Disabilita Fortran esplicitamente
        echo "set(CMAKE_DISABLE_FIND_PACKAGE_Fortran TRUE)" >> deps/Eigen3/CMakeLists.txt

    - name: Set up Python 3.11.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.8

    - name: Install MSVC Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install CMake and Ninja (latest)
      uses: lukka/get-cmake@latest

    - name: Configure CMake (Disable Fortran)
      shell: bash
      run: |
        mkdir -p src_py/build
        cd src_py/build
        cmake .. -G "Ninja" \
          -DCMAKE_BUILD_TYPE=Release \
          -DPYTHON_EXECUTABLE="${{ steps.python-location.outputs.path }}" \
          -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON \
          -DCMAKE_DISABLE_FIND_PACKAGE_Fortran=ON

    - name: Build Project
      shell: bash
      run: |
        cd src_py/build
        cmake --build . --config Release

    - name: Test Import
      shell: bash
      run: |
        cd src_py/distrib/G2lib/G2lib
        python -c "import sys; sys.path.insert(0, '.'); import G2lib; print('Import successful')"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: G2lib-module
        path: src_py/distrib/G2lib/G2lib/*
