name: Build Python Wrapper for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Eigen3
      shell: bash
      run: |
        mkdir -p deps
        rm -rf deps/Eigen3
        git clone -b 3.4 --depth 1 https://gitlab.com/libeigen/eigen.git deps/Eigen3
        sed -i '/enable_language(Fortran)/d' deps/Eigen3/test/CMakeLists.txt

    - name: Set up Python 3.11.8
      uses: actions/setup-python@v4
      id: python-setup
      with:
        python-version: 3.11.8

    - name: Install MSVC Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install CMake 3.28
      uses: lukka/get-cmake@latest
      with:
        version: 3.28.5

    - name: Configure CMake (Python fix)
      shell: bash
      run: |
        mkdir -p src_py/build
        cd src_py/build
        
        # Ottieni il percorso Python corretto
        PYTHON_PATH="${{ steps.python-setup.outputs.python-path }}"
        PYTHON_EXE="$PYTHON_PATH/python.exe"
        
        cmake .. -G "Ninja" \
          -DCMAKE_BUILD_TYPE=Release \
          -DPYTHON_EXECUTABLE="$PYTHON_EXE" \
          -DPython_EXECUTABLE="$PYTHON_EXE" \
          -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON \
          -DCMAKE_CXX_STANDARD=17 \
          -Dpybind11_FIND_DEBUG=ON \
          -Wno-dev

    - name: Build Project
      shell: bash
      run: |
        cd src_py/build
        cmake --build . --config Release --target install

    - name: Test Import
      shell: bash
      run: |
        cd src_py/distrib/G2lib/G2lib
        "${{ steps.python-setup.outputs.python-path }}/python" -c "import G2lib; print('Import success!')"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: G2lib-package
        path: src_py/distrib/G2lib/G2lib/*
