name: Build Python Wrapper for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Eigen3 (patched)
      shell: bash
      run: |
        mkdir -p deps
        rm -rf deps/Eigen3
        git clone -b 3.4 --depth 1 https://gitlab.com/libeigen/eigen.git deps/Eigen3
        sed -i '/enable_language(Fortran)/d' deps/Eigen3/test/CMakeLists.txt
        sed -i 's/add_subdirectory(test)/#add_subdirectory(test)/' deps/Eigen3/CMakeLists.txt

    - name: Set up Python 3.11.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.8

    - name: Install MSVC Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install CMake 3.27
      uses: lukka/get-cmake@latest
      with:
        version: 3.27.9

    - name: Patch pybind11
      shell: bash
      run: |
        sed -i 's/cmake_minimum_required(VERSION 3.4)/cmake_minimum_required(VERSION 3.5)/' src_py/deps/pybind11/CMakeLists.txt

    - name: Configure CMake
      shell: bash
      run: |
        mkdir -p src_py/build
        cd src_py/build
        cmake .. -G "Ninja" \
          -DCMAKE_BUILD_TYPE=Release \
          -DPYTHON_EXECUTABLE="${{ steps.python-location.outputs.path }}" \
          -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON \
          -DCMAKE_CXX_STANDARD=17 \
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
          -Wno-dev

    - name: Build Project
      shell: bash
      run: |
        cd src_py/build
        cmake --build . --config Release --target install

    - name: Test Import
      shell: bash
      run: |
        cd src_py/distrib/G2lib/G2lib
        python -c "import sys, os; sys.path.insert(0, os.getcwd()); import G2lib; print('Import successful!')"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: G2lib-package
        path: src_py/distrib/G2lib/G2lib/*
